/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import org.junit.jupiter.api.Test;


public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
